### ISSUE TITLE
Ngrok Traceback Error

### ISSUE THREAD

**Issue by damndanielll** [graylagx2/GoPhish#1]
[*] Starting the clone server...
                                                                                                                     
[*] Starting ngrok...                                                                                                
Traceback (most recent call last):                                                                                   
  File "/usr/local/bin/gophish", line 33, in <module>                                                                
    sys.exit(load_entry_point('GoPhish', 'console_scripts', 'gophish')())                                            
  File "/home/corona/GoPhish/src/gophish/__main__.py", line 47, in main                                              
    link = start.get_link                                                                                            
  File "/home/corona/GoPhish/src/gophish/gophish.py", line 170, in get_link                                          
    driver = webdriver.Firefox(options=options, executable_path=f'{self.resources}/binaries/geckodriver', service_log_path=f'{self.resources}/logs/geckodriver.log')                                                                      
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__               
    RemoteWebDriver.__init__(                                                                                        
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__                
    self.start_session(capabilities, browser_profile)                                                                
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session           
    response = self.execute(Command.NEW_SESSION, parameters)                                                         
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute                 
    self.error_handler.check_response(response)                                                                      
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response       
    raise exception_class(message, screen, stacktrace)                                                               
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

**Comment by lambert45545** [comment]
the same  issue did u find  a sol

**Comment by CrumplesHQ** [comment]
Same issue here!
